/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

import * as React from 'react';
import { RequireConfig, PageModule } from '../../types/require';
import generate from './generate';
import JavaScriptHighlighter from '../../JavaScriptHighlighter';
import styles from './ConfigGen.css';
import instructionsHTML from '../../../docs/panels/PostBundleInstructions.md';

type Props = {
    pageModules: PageModule[];
    requireConfig: RequireConfig;
};

export default class ConfigGen extends React.PureComponent<Props> {
    markdownWrapperEl = React.createRef<HTMLDivElement>();

    componentDidMount() {
        const { markdownWrapperEl, onMarkdownLinkClick } = this;
        markdownWrapperEl.current!.addEventListener(
            'click',
            onMarkdownLinkClick,
        );
    }

    componentWillUnmount() {
        const { markdownWrapperEl, onMarkdownLinkClick } = this;
        markdownWrapperEl.current!.removeEventListener(
            'click',
            onMarkdownLinkClick,
        );
    }

    onMarkdownLinkClick(e: Event) {
        if ((e.target as HTMLElement).nodeName === 'A') {
            e.preventDefault();
            const href = (e.target as HTMLAnchorElement).href;
            window.open(href, '_blank', 'noopener');
        }
    }

    generateJS() {
        const { pageModules, requireConfig } = this.props;
        const config = generate(pageModules, requireConfig);
        const code = JSON.stringify(config, null, 4);
        return transforms.reduce((code: string, transform) => {
            return transform(code);
        }, code);
    }

    render() {
        return (
            <div className={styles.wrapper}>
                <JavaScriptHighlighter
                    code={this.generateJS()}
                    className={styles.codeView}
                />
                <div
                    className={styles.instructionsWrapper}
                    ref={this.markdownWrapperEl}
                >
                    <div
                        className={styles.instructions}
                        dangerouslySetInnerHTML={{ __html: instructionsHTML }}
                    />
                </div>
            </div>
        );
    }
}

const transforms = [
    parenWrap
];

function parenWrap(code: string) {
    return `${code}`;
}

function addConfigReference(code: string) {
    const d = new Date();
    return `// AUTOGENERATED CONFIGURATION (${d.toDateString()} ${d.toTimeString()})
// Full config reference:
// https://github.com/requirejs/r.js/blob/b8a6982/build/example.build.js

${code}`;
}
